"""
Django settings for example project.

Generated by Cookiecutter Django Package
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

SECRET_KEY = "=bodvqgkt@)emfe2!($i#1zd(x27@u!9*9+)^$8bu#sqsmm^*n"

DEBUG = True

ALLOWED_HOSTS = ["*"]

USE_I18N = True

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sites",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "compressor",
    "example",
    "dac.themes.bs5",
    "dac",
    "dac.addons.allauth",
    "dac.addons.stripe",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.orcid",
    "allauth.mfa",
    "allauth.usersessions",
    "easy_icons",
    "crispy_forms",
    "crispy_bootstrap5",
    "debug_toolbar",
    "flex_menu",
    "django_cotton",
    "cotton_bs5",
    "rest_framework",
    "drf_stripe",
    # "actstream",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = "example.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

AUTH_PASSWORD_VALIDATORS = []

STATIC_URL = "/static/"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    },
}

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

SOCIALACCOUNT_PROVIDERS = {
    "orcid": {
        "BASE_DOMAIN": "sandbox.orcid.org",  # for the sandbox API
    },
    "github": {"VERIFIED_EMAIL": True},
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    },
}

INTERNAL_IPS = [
    "127.0.0.1",
]


# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = COMPRESS_ROOT = str(BASE_DIR / "static")

# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = COMPRESS_URL = "/static/"

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    # other finders..
    "compressor.finders.CompressorFinder",
)

STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

COMPRESS_ENABLED = False
COMPRESS_OFFLINE = False
COMPRESS_STORAGE = "compressor.storage.GzipCompressorFileStorage"
COMPRESS_FILTERS = {
    "css": [
        "compressor.filters.css_default.CssAbsoluteFilter",
        "compressor.filters.cssmin.rCSSMinFilter",
    ],
    "js": ["compressor.filters.jsmin.JSMinFilter"],
}
COMPRESS_PRECOMPILERS = (("text/x-scss", "django_libsass.SassCompiler"),)
LIBSASS_SOURCEMAPS = True


# ======= DRF Stripe Subscription =======

DRF_STRIPE = {
    "STRIPE_API_SECRET": os.environ.get("STRIPE_SECRET_KEY"),  # Replace with your actual Stripe Secret Key
    "STRIPE_WEBHOOK_SECRET": os.environ.get("STRIPE_WEBHOOK_SECRET"),  # Replace with your actual Webhook Secret
    "FRONT_END_BASE_URL": "http://localhost:8000",  # Adjust based on your frontend setup
}


STRIPE_PRICING_TABLE_ID = "prctbl_1RH3JiQrz3Ww3AL2Air6FnEx"
STRIPE_PUBLIC_KEY = "pk_test_51RGyRcQrz3Ww3AL29Iwcjvz650cLcZ87ZEHpPLyLocWmWHvfjHUw3gf976l0EqbXIIVLXRnSbPOl5h4rjG2m6yS1003UKRNEx6"  # Replace with your actual Stripe Public Key


# ======= Allauth Settings =======
LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/account-center/"

EASY_ICONS = {
    "aliases": {
        "github": "fab fa-github",
        "google": "fab fa-google",
        "orcid": "fab fa-orcid",
        "delete": "delete.svg",
        "lock": "lock.svg",
        "check_circle": "check_circle.svg",
        "account_center": "dac.svg",
    },
}

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
