"""
Django settings for example project.

Generated by Cookiecutter Django Package
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from .allauth_settings import *

load_dotenv()

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

SECRET_KEY = "=bodvqgkt@)emfe2!($i#1zd(x27@u!9*9+)^$8bu#sqsmm^*n"

DEBUG = True

ALLOWED_HOSTS = ["*"]

USE_I18N = True

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sites",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "dac",
    "dac.allauth",
    "mvp",
    "example",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.orcid",
    "allauth.mfa",
    "allauth.usersessions",
    "easy_icons",
    "crispy_forms",
    "flex_menu",
    "django_cotton",
    "django_extensions",
    "django_browser_reload",
    "dj_urls_panel",
    "crispy_tailwind",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "django.contrib.sites.middleware.CurrentSiteMiddleware",
]

ROOT_URLCONF = "example.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "mvp.context_processors.mvp_config",
            ],
        },
    },
]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

AUTH_PASSWORD_VALIDATORS = []

STATIC_URL = "/static/"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    },
}

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = ["tailwind"]

CRISPY_TEMPLATE_PACK = "tailwind"


# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = COMPRESS_ROOT = str(BASE_DIR / "static")

# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = COMPRESS_URL = "/static/"

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# ======= Allauth Settings =======
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "/account-center/"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

if SOCIALACCOUNT_ONLY:
    INSTALLED_APPS.remove("allauth.mfa")
    ACCOUNT_EMAIL_VERIFICATION = "none"


# settings.py
DJ_URLS_PANEL_SETTINGS = {
    # Exclude specific URL patterns
    "EXCLUDE_URLS": [
        r"^admin/",  # Exclude admin URLs
        r"^__debug__/",  # Exclude debug toolbar
    ],
    # Enable/disable URL testing interface
    "ENABLE_TESTING": True,  # Set to False in production
    # Whitelist hosts for URL testing (SSRF protection)
    "ALLOWED_HOSTS": None,  # or ['yourdomain.com']
}


FLEX_MENUS = {
    "renderers": {
        "sidebar": "mvp.renderers.SidebarRenderer",
        "dock": "mvp.renderers.MobileFooterNavRenderer",
    },
    "log_url_failures": DEBUG,
}

MVP_CONFIG = {
    "layout": {
        "sidebar": {
            "title": "DAC Example",
            # The authenticated user menu (bottom of the sidebar) is where the
            # "Account Center" entry appears once dac's URLs are installed.
            "footer": ["user.sidebar-menu"],
        },
    },
}

EASY_ICONS = {
    # Default renderer - used when no renderer specified.
    "default": {
        "renderer": "easy_icons.renderers.ProviderRenderer",
        "config": {"tag": "i"},
        "packs": ["mvp.utils.BS5_ICONS", "dac.icons.DAC_ICONS"],
    },
    # Social-login brand icons. dac.allauth ships the SVGs (its icons/ dir);
    # provider.html renders them via {% icon provider_id renderer="svg" %}.
    # Override a mark by re-pointing its entry here or shadowing the template.
    "svg": {
        "renderer": "easy_icons.renderers.SvgRenderer",
        "config": {"default_attrs": {"height": "1.25em", "width": "1.25em"}},
        "icons": {
            "google": "google.svg",
            "github": "github.svg",
            "microsoft": "microsoft.svg",
            "apple": "apple.svg",
            "facebook": "facebook.svg",
            "twitter": "x.svg",
            "twitter_oauth2": "x.svg",
            "linkedin": "linkedin.svg",
            "linkedin_oauth2": "linkedin.svg",
            "gitlab": "gitlab.svg",
            "discord": "discord.svg",
            "orcid": "orcid.svg",
        },
    },
}
