"""Write the Tailwind source paths for django-mvp, resolved from the installed package.

The stylesheet build needs django-mvp's Tailwind preset and its template tree. Pointing at
them with a relative path assumed a sibling checkout of the django-mvp repository, so the
build only ran on a machine that happened to have one, and it scanned whatever unreleased
state that checkout was in rather than the pinned release.

Run by `npm run build:css` (as its `pre` step). Output is generated, not committed.
"""

import pathlib

import mvp

OUTPUT = pathlib.Path(__file__).parent / "_sources.css"

# mvp is a namespace-style package, so __path__ is the reliable locator, not __file__.
mvp_dir = pathlib.Path(next(iter(mvp.__path__))).resolve()

OUTPUT.write_text(
    f"""/* Generated by resolve_sources.py — do not edit, do not commit. */

/* django-mvp's shared preset (custom variants, runtime-class safelist). */
@import "{mvp_dir}/tailwind/base.css";

/* mvp's templates, so dac pages can use utilities beyond the ones
   django-mvp.css happens to include. */
@source "{mvp_dir}";
""",
    encoding="utf-8",
)

print(f"resolved django-mvp to {mvp_dir}")
